# Generated by Django 5.0.7 on 2024-12-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0003_journal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
