# Generated by Django 5.0.7 on 2024-12-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0005_alter_journalentry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
